config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login', to: 'sessions#new'
  post'/login', to: 'sessions#create'
  delete'/logout', to: 'sessions#destroy'

  get 'users/new'
  get 'users/myarticles' => 'users#articles', :as => :user_articles

  resources :users
  resources :articles do
    member do
      post 'Like'
    end  
  end
  root 'sessions#new'

end

app/models/article.rb
class Article < ActiveRecord::Base

	has_many :likes, class_name: 'Like', dependent: :destroy

	has_many :articles, dependent: :destroy

	belongs_to :user

	validates :title, presence: true, length: { minimum: 5 } 
end

app/models/like.rb
class Like < ActiveRecord::Base

 belongs_to :article

 belongs_to :user

 validates_uniqueness_of :article_id, scope: :user_id


end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base

  has_many :likes, :through => :posts, dependent: :destroy

  has_many :articles, dependent: :destroy

attr_accessor :remember_token

validates :name, presence: true
VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true,
           format: { with: VALID_EMAIL},
           uniqueness: { case_sensitive: false}

#has_secure_password
#  validates :password, presence: true


 def User.digest(string)

    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                BCrypt::Engine.cost
   BCrypt::Password.create(string)
 end

 def User.new_token
    SecureRandom.urlsafe_base64
 end
 
 def remember
    self.remember_token = User.new_token

    update_attribute(:remember_digest, User.digest(remember_token))
    #puts cookies
    #cookies.permanent[:remember_token] = user.remember_token
 end

def authenticated?(remember_token)
	return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
end

def forget
    update_attribute(:remember_digest, nil)
end

end

app/models/userinfo.rb
class Userinfo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
 
 before_action :logged_in_user

 def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def create
    #@article = Article.new(article_params)

    #@article = Article.new(article_params).merge(:user_id => current_user.id)
    puts current_user.name
    @article = current_user.articles.build(article_params)
    #@like = @article.likes.build(article_params)

    if @article.save
     redirect_to @article
    else
     render 'new'
   end
  end
   
  def update
    @article = Article.find(params[:id])
    
    if @article.update(article_params)
       redirect_to @article
    else
       render 'edit'
    end
  end 

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  def Like
    #@user = current_user
    @article = Article.find(params[:id])
   # like = Like.new
   #like.article_id = @article.id
   # like.user_id = current_user.id
   # like.save!
    #@users = @user.likes.build(params[:id])
    if @article.likes.create(user_id: current_user.id)
       redirect_to(articles_path)
    else
       flash[:notice] =  "already liked!"
       redirect_to(articles_path)
    end
    #@user.Like!(@article)
    #@user = current_user
    #@article = current_user.likes.build(article_params)
      #flash[:notice] =  "already liked!"
      #redirect_to(articles_path)

  end

  private
    def article_params
      params.require(:article).permit(:title, :text, :user_id)
    end  

  def logged_in_user
      unless logged_in?
        flash[:sorry] = "Please log in"
        redirect_to login_path
      end
    end   
end

 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
  	puts "========================"
  	puts params[:session][:email]

  user = User.find_by(email: params[:session][:email].downcase)

  #if user && user.authenticate(params[:session][:password])
    if user.present? && user.valid?  
       log_in user
       remember user
       #redirect_to user
       redirect_to articles_path 

    else
      flash.now[:danger] = 'Invalid email/password combination'  
  	  render 'new'
  end

  end

  def destroy
    log_out

    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #before_action :logged_in_user

  def new
  	 @user = User.new

  end
  
  def show
  	@user = User.find(params[:id])
  end
  
  def articles
    #@user = User.find(params[:id])
    @user = current_user
    puts @user
    puts current_user.name
    @articles = @user.articles
  end  

  def create
    @user = User.new
   
        @user.name = params[:users][:username]
		

		@user.email = params[:users][:email]
		

		@user.password = params[:users][:password]

    
    if @user.save
			log_in @user
			flash[:notice] = "You signed up successfully"
			#flash[:color] = "valid"
			redirect_to articles_path
			#redirect_to @user
        else
        	flash[:notice] = "Form is invalid"
        	#flash[:color] = "invalid"
        	render "new"
        end


  end

  #def logged_in_user
  #    unless logged_in?
  #      flash[:sorry] = "Please log in"
  #      redirect_to login_path
  #    end
  #  end   

# def user_params
# 	params.require(:user).permit(:name ,:email, :password)
# end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

def log_in(user)
    session[:user_id] = user.id

    puts session[:user_id]
end

def current_user
	puts "==========================================="
    #@current_user ||= User.find_by(id: session[:user_id])
    puts session[:user_id]
    puts @current_user

    puts "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
     if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
      puts @current_user.name
      puts "###!!!!!!!!!!!!!!!!!!!!!!!!"
    elsif (user_id = cookies.signed[:user_id])
      puts user_id
      user = User.find_by(id: user_id)
      puts "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
      if user && user.authenticated?(cookies[:remember_token])
        puts "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
        log_in user
        @current_user = user
      end
    end
    return @current_user
end

#def current_user?(user)
#	user == current_user
#end	

def logged_in?
	puts "+++++++++++++++++++++++++++++++++++++++++++++"
	!current_user.nil?
end

#def log_out
#	puts"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
#	session.delete(:user_id)
#	@current_user = nil
#end

def log_out
  forget(current_user)
  puts "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
  puts session
    session.delete(session[:user_id])
    session[:user_id] = nil
    puts session[:user_id]
    #user_id = session[:user_id]
    #puts user_id
    @current_user = nil
    puts @current_user
end


def remember(user)
  puts "**********************************************"
	user.remember
  puts "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
	cookies.permanent.signed[:user_id]=user.id
  cookies.permanent[:remember_token] = user.remember_token
end

def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= form_for @article do |f| %>

<% if @article.errors.any? %>
     <div id="error_explanation">
       <h2>
          <%= pluralize(@article.errors.count, "error") %>
prohibited
          this article from being saved:
       </h2>
       <ul>
         <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
       </ul>
    </div>
   <% end %>      



  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%=f.label :text %><br>
    <%=f.text_area :text %>
  </p>

  <p>
    <%=f.submit %>
  </p>
  <% end %>

  <%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<%= link_to 'New Article', new_article_path %>
<%= link_to 'My Articles', user_articles_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= pluralize(article.likes.count,"Like") %></td>
      <td><%= button_to '+1', Like_article_path(article),method: :post %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article), 
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<p>Log out? <%= link_to "Log out!", logout_path , method: :delete %></p>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_for @article do |f| %>

<% if @article.errors.any? %>
     <div id="error_explanation">
       <h2>
          <%= pluralize(@article.errors.count, "error") %>
prohibited
          this article from being saved:
       </h2>
       <ul>
         <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
       </ul>
    </div>
   <% end %>

<p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%=f.label :text %><br>
    <%=f.text_area :text %>
  </p>

  <p>
    <%=f.submit %>
  </p>
  <% end %>

  <%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>



<%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class = "container">
    <% flash.each do |message_type,message| %>
       <div class = "alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
<%= yield %>

</body>
</html>

app/views/users/articles.html.erb
<h1>My Articles</h1>

<!--<% @articles.each do |article| %>
  <%= article.inspect %>
<% end %>-->


<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
    </tr>
  <% end %>
  </table>

<%= link_to 'Back', articles_path %>

app/views/users/new.html.erb
<% @page_title = "SIGN UP" %>
 <div class="Sign_Form">
  
  <h1>Sign Up Here</h1>
  <%= form_for :users , url: signup_path do |f| %>

    <p> Username:</br> <%= f.text_field :username%> </p>
    
    <p> Email:</br> <%= f.text_field :email%> </p>
    
    <p> Password:</br> <%= f.password_field :password%></p>
    
    <%= f.submit :Signup %>
  
  <% end %>
  
  <% if @user.errors.any? %>
    
    <ul class="Signup_Errors">
    
    <% for message_error in @user.errors.full_messages %>
      
      <li>* <%= message_error %></li>
    
    <% end %>
    
    </ul>
  
  <% end %>

</div>